name: 'teste_dremio_dbt'
version: '1.0.0'
config-version: 2

profile: 'teste_dremio_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  teste_dremio_dbt:

    # =========================================================
    # STAGING (Camada de Limpeza / Raw)
    # Destino: base.xml.camada_raw ou base.icms.camada_raw
    # =========================================================
    staging:
      +database: base
      +materialized: view

      xml_nfe:
        +schema: xml.camada_raw

      icms:
        +schema: icms.camada_raw

    # =========================================================
    # MARTS (Camada de Negócio / Consumo)
    # Destino: base.xml.camada_consumo ou base.icms.camada_consumo
# =========================================================
    # MARTS (Camada de Negócio / Consumo)
    # =========================================================
    marts:
      +database: base
      +materialized: view

      xml_nfe:
        +schema: xml.camada_consumo

      icms:
        +schema: icms.camada_consumo

      consolidado:
        +schema: consolidado # Aqui ele deve criar base.consolidado.fct...