teste_dremio_dbt:
  target: dev
  outputs:
    dev:
      type: dremio
      software_host: 'dremio'
      port: 9047
      user: 'suporte'
      password: "{{ env_var('DBT_PASSWORD') }}"
      auth_type: 'username_password'
      use_ssl: false
# No Dremio OSS, o 'database' deve ser DREMIO ou o nome do seu Space
      database: "DREMIO" 
      # O schema com @ indica o seu espaço pessoal (Home)
      schema: "@suporte"
  models:
  teste_dremio_dbt:
    staging:
      nfe_mysql:
        +tags: "xml-nfe"   # Tudo que vier do MySQL ganha essa tag
      nfe_s3_parquet:
        +tags: "icms"      # Tudo que vier do Parquet ganha essa tag