teste_dremio_dbt:
  target: dev
  outputs:
    dev:
      type: dremio
      # Tente usar software_host ou dremio_host (alguns builds mudam isso)
      software_host: "dremio" 
      port: 9047
      user: "suporte"
      password: "L0c@L123"
      # O dbt 1.10 às vezes exige esses campos explicitamente:
      database: "base"
      schema: "@suporte"
      software_edition: "software"
      use_ssl: false