version: 2

models:
  - name: stg_prod
    description: "Dados dos produtos extraídos diretamente do banco de dados de emissão (XML). Nossa 'Verdade Absoluta'."
    
  - name: stg_icms
    description: "Detalhamento do imposto calculado no momento da emissão da nota no MySQL."

  - name: stg_log
    description: "Histórico de processamento. Filtramos aqui apenas notas com status 'Autorizada' para o confronto."